# include: package:flutter_lints/flutter.yaml

# analyzer:
#   exclude:
#     - build/**
#     - packages/module_codegen/**
#   strong-mode:
#     implicit-casts: false
#     implicit-dynamic: false
#   errors:
#     todo: warning
#     missing_return: error

# linter:
#   rules:
#     prefer_single_quotes: true # Uncomment to enable the `prefer_single_quotes` rule

# added module_analyzer

include: package:module_analyzer/analysys_options.yaml
