name: catch_error
description: A new Flutter project.

publish_to: "none"
version: 1.0.0+1

environment:
    sdk: ">=2.17.0 <3.0.0"

dependencies:
    flutter:
        sdk: flutter
    cupertino_icons: ^0.1.3

dev_dependencies:
    flutter_lints: ^2.0.1
    flutter_test:
        sdk: flutter
    import_sorter: ^4.6.0

flutter:
    assets:
        - assets/
    uses-material-design: true
