// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDynVgbl3OlLU1BOriqK2QHGLVV_8j_S08',
    appId: '1:255258696051:web:87242d6c78be968ddf8d06',
    messagingSenderId: '255258696051',
    projectId: 'flutter-demo-bddeb',
    authDomain: 'flutter-demo-bddeb.firebaseapp.com',
    storageBucket: 'flutter-demo-bddeb.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBhdYAcurlItd7MvLuRFERKnwfmFIkeW4g',
    appId: '1:255258696051:android:44136fbc44d5ed98df8d06',
    messagingSenderId: '255258696051',
    projectId: 'flutter-demo-bddeb',
    storageBucket: 'flutter-demo-bddeb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBgv3dvzpz56f2eUcZq0pz2xDDdyl-pC0o',
    appId: '1:255258696051:ios:a89d718814b05491df8d06',
    messagingSenderId: '255258696051',
    projectId: 'flutter-demo-bddeb',
    storageBucket: 'flutter-demo-bddeb.appspot.com',
    iosClientId: '255258696051-pd8d68dednub7vljh4rcdmsigcp08j5s.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplicationFirebase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDynVgbl3OlLU1BOriqK2QHGLVV_8j_S08',
    appId: '1:255258696051:web:71144b4772f8af0fdf8d06',
    messagingSenderId: '255258696051',
    projectId: 'flutter-demo-bddeb',
    authDomain: 'flutter-demo-bddeb.firebaseapp.com',
    storageBucket: 'flutter-demo-bddeb.appspot.com',
  );
}
